# Generated by Django 4.2.1 on 2023-05-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('T', 'Text'), ('I', 'Image'), ('V', 'Video')], default=12, max_length=1),
            preserve_default=False,
        ),
    ]
