# Generated by Django 4.2.1 on 2023-05-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('T', 'Text'), ('I', 'Image'), ('V', 'Video')], max_length=1, null=True),
        ),
    ]
