# Generated by Django 4.2.1 on 2023-05-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
