# Generated by Django 4.2.1 on 2023-05-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_post_post_post_image_post_post_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
